image:
  name: sonarsource/sonar-scanner-cli:11
  entrypoint: [""]

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  GIT_SSL_NO_VERIFY: "1"
  # Desactiva el clone/pull automático de GitLab Runner:
  GIT_STRATEGY: "none"

stages:
  - build-sonar

build-sonar:
  stage: build-sonar
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/

  script:
    # 1) Clona manualmente por HTTPS usando el CI_JOB_TOKEN
    - git clone https://oauth2:${CI_JOB_TOKEN}@repo.dicrep.gob.cl/${CI_PROJECT_PATH}.git .
    # 2) Entra al directorio y ejecuta Sonar
    - cd frontend_sala_ventas
    - sonar-scanner \
        -Dsonar.projectBaseDir=. \
        -Dsonar.host.url="${SONAR_HOST_URL}" \
        -Dsonar.login="${SONAR_TOKEN}"

  allow_failure: true

  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'
